SELECT USER
FROM DUAL;
--==>> SCOTT

--TBL_EMP, TBL_BUSEO, TBL_CITY, TBL_JIKWI, TBL_EMP

CREATE VIEW VIEWEMP2
AS
SELECT E.EMP_ID, E.EMP_NAME, E.SSN, E.IBSADATE, C.CITY_LOC, E.TEL
     , B.BUSEO_NAME, J.JIKWI_NAME, J.MIN_BASICPAY, E.BASICPAY, E.SUDANG
     , (E.BASICPAY+E.SUDANG) AS PAY
FROM TBL_EMP E, TBL_CITY C, TBL_BUSEO B, TBL_JIKWI J
WHERE E.CITY_ID = C.CITY_ID
  AND E.BUSEO_ID = B.BUSEO_ID
  AND E.JIKWI_ID = J.JIKWI_ID;
--==>> View VIEWEMP2이(가) 생성되었습니다.

--1. 지역리스트 조회 쿼리문
-- 직원 정보 입력 과정에서 안내해야 할 리스트
SELECT CITY_LOC FROM TBL_CITY
;
--2. 부서리스트 조회 쿼리문
-- 직원 정보 입력 과정에서 안내해야 할 리스트
SELECT BUSEO_NAME FROM TBL_BUSEO
;

--3. 직위리스트 조회 쿼리문
-- 직원 정보 입력 과정에서 안내해야 할 리스트
SELECT JIKWI_NAME FROM TBL_JIKWI
;

--4. 최소기본급 조회 쿼리문
SELECT MIN_BASICPAY FROM TBL_JIKWI WHERE JIKWI_NAME = '부장'
;

--5. 데이터 입력 쿼리문 
-- 직원 정보 입력 데이터의 형태
INSERT INTO TBL_EMP (EMP_ID, EMP_NAME, SSN, IBSADATE, CITY_ID, TEL, BUSEO_ID, JIKWI_ID, BASICPAY, SUDANG) 
VALUES ( EMPSEQ.NEXTVAL, '김아별', '930307-2234567', TO_DATE('2020-03-12', 'YYYY-MM-DD')
      , (SELECT CITY_ID FROM TBL_CITY WHERE CITY_LOC = '인천')
      , '010-7777-2222'
      , (SELECT BUSEO_ID FROM TBL_BUSEO WHERE BUSEO_NAME = '개발부')
      , (SELECT JIKWI_ID FROM TBL_JIKWI WHERE JIKWI_NAME = '대리')
      , 200000
      , 20000 );

--> 한 줄 구성
INSERT INTO TBL_EMP (EMP_ID, EMP_NAME, SSN, IBSADATE, CITY_ID, TEL, BUSEO_ID, JIKWI_ID, BASICPAY, SUDANG) VALUES ( EMPSEQ.NEXTVAL, '김아별', '930307-2234567', TO_DATE('2020-03-12', 'YYYY-MM-DD'), (SELECT CITY_ID FROM TBL_CITY WHERE CITY_LOC = '인천'), '010-7777-2222', (SELECT BUSEO_ID FROM TBL_BUSEO WHERE BUSEO_NAME = '개발부'), (SELECT JIKWI_ID FROM TBL_JIKWI WHERE JIKWI_NAME = '대리'), 200000, 20000 );

--6. 직원 전체 출력(사번/이름/부서/직위/급여 내림차순 정렬)
SELECT EMP_ID, EMP_NAME, SSN, TO_CHAR(IBSADATE, 'YYYY-MM-DD') AS IBSADATE, CITY_LOC, TEL,BUSEO_NAME, JIKWI_NAME
    , MIN_BASICPAY, BASICPAY, SUDANG, PAY
FROM EMPVIEW
ORDER BY EMP_ID;
         --EMP_NAME;
         --BUSEO_NAME;
         --JIKWI_NAME;
         --PAY DESC;

-->한줄 구성
SELECT EMP_ID, EMP_NAME, SSN, TO_CHAR(IBSADATE, 'YYYY-MM-DD') AS IBSADATE, CITY_LOC, TEL,BUSEO_NAME, JIKWI_NAME, MIN_BASICPAY, BASICPAY, SUDANG, PAY FROM EMPVIEW ORDER BY EMP_ID
;

--7. 직원 검색 출력(사번/이름/부서/직위)
SELECT EMP_ID, EMP_NAME, SSN, TO_CHAR(IBSADATE, 'YYYY-MM-DD') AS IBSADATE, CITY_LOC, TEL,BUSEO_NAME, JIKWI_NAME
    , MIN_BASICPAY, BASICPAY, SUDANG, PAY
FROM EMPVIEW
WHERE EMP_ID = 1001;
      --EMP_NAME = '홍길동';

--한줄 구성
SELECT EMP_ID, EMP_NAME, SSN, TO_CHAR(IBSADATE, 'YYYY-MM-DD') AS IBSADATE, CITY_LOC, TEL, BUSEO_NAME, JIKWI_NAME, BASICPAY, SUDANG, PAY FROM EMPVIEW WHERE EMP_ID=1001
;

--8. 전체 직원수 출력
SELECT COUNT(*) AS COUNT FROM EMPVIEW
;

--9. 검색 직원수 출력
SELECT COUNT(*) AS COUNT FROM EMPVIEW WHERE EMP_ID = 1001
;


--10. 직원정보 수정
UPDATE TBL_EMP SET EMP_NAME = '홍길동', SSN = '771212-1022433', IBSADATE = TO_DATE('1999-11-11','YYYY-MM-DD'), CITY_ID = (SELECT CITY_ID FROM TBL_CITY WHERE CITY_LOC = '서울'), TEL = '010-1111-1111', BUSEO_ID = (SELECT BUSEO_ID FROM TBL_BUSEO WHERE BUSEO_NAME = '기획부'), JIKWI_ID = (SELECT JIKWI_ID FROM TBL_JIKWI WHERE JIKWI_NAME = '부장'), BASICPAY = 3000000, SUDANG = 500000 WHERE EMP_ID = 1001
;
-- 11. 직원 데이터 삭제 쿼리문 구성
DELETE FROM TBL_EMP WHERE EMP_ID = 1011
;












